
image:
  file: .devcontainer/Dockerfile
tasks:
  - init: pip install -r requirements.txt
    command: python main.py
vscode:
  extensions:
    - ms-python.python
    - mtxr.sqltools
    - rangav.vscode-thunder-client
